name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change to 'master' if your default branch is named 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Generate config.json with API key
        run: |
          echo '{"api_key": "${{ secrets.PIXABAY_API_KEY }}"}' > assets/config.json

      - name: Build Flutter web app
        run: flutter build web --release

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Make sure this secret is set
          publish_dir: ./build/web
          force_orphan: true  # Create a new orphan branch
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy to GitHub Pages'
