name: PixGallery

on:
  push:
    branches:
      - main  # Or your default branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Set Flutter 3.10.6'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.10.6

      - name: 'Checkout Flutter 3.10.7'
        shell: bash
      - run: |
          cd $FLUTTER_ROOT;
          git fetch --tags;
          git checkout 3.10.7;
          flutter --version;


      - name: Install dependencies
        run: flutter pub get

      - name: Inject API Key
        run: echo "const String apiKey = '${{ secrets.PIXABAY_API_KEY }}';" > lib/utils/constants.dart

      - name: Build Flutter web app
        run: flutter build web --release

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
