name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Generate config.json with API key
        run: |
          echo '{"api_key": "${{ secrets.PIXABAY_API_KEY }}"}' > assets/config.json

      - name: Build Flutter web app
        run: flutter build web --base-href "/PixGallery/" --release

      - name: Remove old gh-pages files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git clone --depth=1 --branch gh-pages https://github.com/${{ github.repository }} gh-pages
          cd gh-pages
          rm -rf *
          cd ..

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
