name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.2.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Generate config.json with API key
        run: |
          echo '{"api_key": "${{ secrets.PIXABAY_API_KEY }}"}' > assets/config.json

      - name: Build Flutter web app
        run: flutter build web --release

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
